//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATVEKOLOGIN
    {
        public string idUser2 { get; set; }
        public string HoTen2 { get; set; }
        public string GioiTinh2 { get; set; }
        public string Sdt2 { get; set; }
        public string Email2 { get; set; }
        public Nullable<System.DateTime> NgayDat2 { get; set; }
        public string idVe { get; set; }
        public string tienthanhtoan { get; set; }
    
        public virtual VEMAYBAY VEMAYBAY { get; set; }
    }
}
