//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATVE()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string idDatVe { get; set; }
        public string idUser { get; set; }
        public Nullable<System.DateTime> NgayDatVe { get; set; }
        public string idVe { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual VEMAYBAY VEMAYBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
