//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEMAYBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEMAYBAY()
        {
            this.DATVEs = new HashSet<DATVE>();
            this.DATVEKOLOGINs = new HashSet<DATVEKOLOGIN>();
        }
    
        public string idVe { get; set; }
        public string idChuyenBay { get; set; }
        public string idLoaiVe { get; set; }
        public Nullable<int> SoKgHanhLy { get; set; }
        public Nullable<int> GiaVe { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATVE> DATVEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATVEKOLOGIN> DATVEKOLOGINs { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
