//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENBAY()
        {
            this.VEMAYBAYs = new HashSet<VEMAYBAY>();
        }
    
        public string idChuyenBay { get; set; }
        public Nullable<System.DateTime> NgayBay { get; set; }
        public string GioBay { get; set; }
        public string GioDen { get; set; }
        public string NoiDi { get; set; }
        public string NoiDen { get; set; }
        public string idMayBay { get; set; }
    
        public virtual MAYBAY MAYBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEMAYBAY> VEMAYBAYs { get; set; }
    }
}
