//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU
    {
        public string idDoanhThu { get; set; }
        public Nullable<System.DateTime> ThangNamTK { get; set; }
        public Nullable<int> TongSoHD { get; set; }
        public Nullable<int> TongDT { get; set; }
    }
}
