//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string idHoaDon { get; set; }
        public Nullable<System.DateTime> NgayXuatHoaDon { get; set; }
        public Nullable<int> TongTienHD { get; set; }
        public string idDatVe { get; set; }
    
        public virtual DATVE DATVE { get; set; }
    }
}
