//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public string idKhuyenMai { get; set; }
        public string MaKhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayBatDauKM { get; set; }
        public Nullable<System.DateTime> NgayKetThucKM { get; set; }
        public string ChiTietMoTaKM { get; set; }
        public Nullable<int> GiaTriKM { get; set; }
    }
}
