//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDatVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAYBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAYBAY()
        {
            this.CHUYENBAYs = new HashSet<CHUYENBAY>();
        }
    
        public string idMayBay { get; set; }
        public string TenMayBay { get; set; }
        public Nullable<int> SoLuongKhach { get; set; }
        public string idHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual HANGMAYBAY HANGMAYBAY { get; set; }
    }
}
